capstone/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopping/', include("shopping.urls"))
]

capstone/shopping/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("signup", views.signup_view, name="signup"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("profile/<str:name>", views.profile_view, name="profile"),
    path(
        "updateprofilepic", views.update_profile_pic,
        name="update_profile_pic"),
    path(
        "updateprofileaddr", views.update_profile_delivery_addr,
        name="update_profile_delivery_addr"),
    path(
        "createlisting", views.create_listing_view,
        name="create_listing"),
    path("listing/<int:listing_id>", views.listing_view, name="listing"),
    path(
        "updateproductdesrc/<int:listing_id>",
        views.update_listing_desrc_view,
        name="update_product_listing"),
    path("review/<int:listing_id>", views.review_view, name="review"),
    path(
        "updatereview/<int:listing_id>", views.update_review_view,
        name="update_review"),
    path("category/<str:category_name>", views.category_view, name="category"),
    path("categorysort", views.category_sort_view, name="categorysort"),
    path("cart", views.cart_view, name="cart"),
    path("updatecart", views.update_cart_view, name="updatecart"),
    path("checkout", views.checkout_view, name="checkout"),
    path("trackorder", views.track_order_view, name="trackorder"),
    path("receiveorder", views.receive_order, name="receive_order"),
    path("cancelorder", views.cancel_order, name="cancel_order"),
    path("returnorder", views.return_order, name="return_order"),
    path(
        "acceptreturn", views.accept_return_order, name="accept_return_order"),
    path(
        "cancelreturn", views.cancel_return_order, name="cancel_return_order"),
    path(
        "notification/<str:name>", views.profile_view_notification_toggled,
        name="notification"),
    path("search", views.search_view, name="search"),
    path("filter", views.filter_category, name="filter_category"),
    path("sort", views.sort_category, name="sort_category"),

    # API Routes
    path(
        "updateprofile/<int:profile_id>", views.update_profile,
        name="updateprofile"),
    path(
        "updateorder/<int:order_id>", views.update_order,
        name="updateorder"),
    path(
        "updatelisting/<int:listing_id>", views.update_listing,
        name="updatelisting"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

capstone/shopping/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class User(AbstractUser):
    order_total_price = models.FloatField(null=True, blank=True)
    has_new_notification = models.BooleanField(default=False)

    def serialize(self):
        return {
            "id": self.id,
            "email": self.email
        }


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="profile")
    full_name = models.CharField(
        max_length=100, blank=False, null=False, default="")
    gender = models.CharField(
        max_length=20, blank=False, null=False, default="Male")
    phone_number = models.IntegerField(
        blank=True, null=False, default=99887766)
    date_of_birth = models.DateField(
        blank=False, null=False, default="2000-12-30")
    profile_pic = models.ImageField(null=True, blank=True)
    delivery_address = models.CharField(
        max_length=200, blank=True, null=True)

    def __str__(self):
        return self.full_name

    def serialize(self):
        return {
            "id": self.id,
            "full_name": self.full_name,
            "gender": self.gender,
            "phone_number": self.phone_number,
            "date_of_birth": self.date_of_birth
        }


class Listing(models.Model):
    CATEGORY = (
        ("Men's Wear", "Men's Wear"),
        ("Women's Apparel", "Women's Apparel"),
        ("Mobile & Gadgets", "Mobile & Gadgets"),
        ("Beauty & Personal Care", "Beauty & Personal Care"),
        ("Home Appliances", "Home Appliances"),
        ("Home & Living", "Home & Living"),
        ("Kids Fashion", "Kids Fashion"),
        ("Toys, Kids & Babies", "Toys, Kids & Babies"),
        ("Video Games", "Video Games"),
        ("Food & Beverages", "Food & Beverages"),
        ("Computers & Peripherals", "Computers & Peripherals"),
        ("Hobbies & Books", "Hobbies & Books"),
        ("Health & Wellness", "Health & Wellness"),
        ("Women's Bags", "Women's Bags"),
        ("Travel & Luggage", "Travel & Luggage"),
        ("Pet Food & Supplies", "Pet Food & Supplies"),
        ("Watches", "Watches"),
        ("Jewellery & Accessory", "Jewellery & Accessory"),
        ("Men's Shoes", "Men's Shoes"),
        ("Women's Shoes", "Women's Shoes"),
        ("Sports & Outdoors", "Sports & Outdoors"),
        ("Automotive", "Automotive"),
        ("Men's Bags", "Men's Bags"),
        ("Cameras & Drones", "Cameras & Drones"),
        ("Dining, Travel & Services", "Dining, Travel & Services"),
        ("Miscellaneous", "Miscellaneous"))

    title = models.CharField(max_length=64)
    desrc = models.TextField()
    category = models.CharField(max_length=64, blank=True, choices=CATEGORY)
    datetime = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(default=0.00, max_digits=20, decimal_places=2)
    listing_main_pic = models.ImageField(null=True, blank=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="listing", default=1)
    rating_score = models.FloatField(
        default=0.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])
    quantity_sold = models.IntegerField(default=0)
    click_rate = models.IntegerField(default=0)
    is_sold_out = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title}"

    def serialize(self):
        return {
            "id": self.id,
            "title": self.title,
            "desrc": self.desrc,
            "date": self.date,
            "quantity": self.quantity,
            "price": self.price,
            "listing_main_pic": self.listing_main_pic,
            "user": self.user,
            "rating_score": self.rating_score,
            "quantity_sold": self.quantity_sold,
            "click_rate": self.click_rate,
            "is_sold_out": self.is_sold_out
        }


class ListingImage(models.Model):
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="images", default=1)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f"{self.image}"


class Order(models.Model):
    STATUS = (
        ("To Ship", "To Ship"),
        ("To Receive", "To Receive"),
        ("Completed", "Completed"),
        ("Cancelled", "Cancelled"),
        ("Return/Refund", "Return/Refund"),
        ("Return Rejected", "Return Rejected"),
    )

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="order",
        null=True, blank=True)
    quantity_demanded = models.IntegerField(default=0)
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="order",
        null=True, blank=True)
    datetime = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    status = models.CharField(
        max_length=64, default="To Ship", choices=STATUS)
    has_purchased = models.BooleanField(default=False)
    is_tracking = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}'s Order: {self.listing}"

    def serialize(self):
        return {
            "id": self.id,
            "quantity_demanded": self.quantity_demanded,
            "status": self.status
        }


class Review(models.Model):
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="review", default=1)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="review", default=1)
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="review", default=1)
    review = models.TextField(null=True, blank=True)
    datetime = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    rating = models.FloatField(
        default=0.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(5.0)])

    def __str__(self):
        return f"{self.user}: {self.listing}"


class Notification(models.Model):
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="notification",
        null=True, blank=True)
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="notification",
        null=True, blank=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notification",
        null=True, blank=True)
    review = models.ForeignKey(
        Review, on_delete=models.CASCADE, related_name="notification",
        null=True, blank=True)
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="notification",
        null=True, blank=True)
    datetime = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    has_read = models.BooleanField(default=False)
    has_action = models.BooleanField(default=False)
    content = models.TextField()

    def __str__(self):
        return f"{self.user}'s Notification"

capstone/shopping/forms.py
from django import forms


class SignUpForm(forms.Form):
    GENDER = [
     ('Male', 'Male'),
     ('Female', 'Female'),
     ('Other', 'Other')
    ]

    full_name = forms.CharField(label="Full Name")
    password = forms.CharField(label="Password")
    gender = forms.ChoiceField(label="Gender", choices=GENDER)
    phone_number = forms.IntegerField(label="Phone Number")
    email = forms.EmailField(label="Email")

    birthday = forms.DateField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker4'
        })
    )


class NewListingForm(forms.Form):
    title = forms.CharField(label="Title of Listing")
    desrc = forms.CharField(label="Description of Listing")
    category = forms.CharField(label="Category of Listing")
    price = forms.FloatField(label="Selling Price of Listing")
    quantity = forms.IntegerField(label="Quantity for Sale")
    image_file = forms.ImageField(label="Listing Images")

capstone/shopping/templates/shopping/login.html
{% extends "shopping/layout.html" %}
{% load static %}

{% block title %}
    Shopping | Log In
{% endblock %}

{% block style %}
    <style>
        .navbar p {
            font-size: 30px;
        }

        #login-btn {
            width: 100%;
            margin-top: 20px;
            background-color: #42f5c2;
            color: white;
        }

        #login-btn:hover {
            background-color: #60dbb9;
        }

        .logo-section {
            color: white;
            text-docoration: none;
        }

        .logo-section-container:hover {
            color: white;
            text-decoration: none;
            color: #60dbb9;
        }

        .logo-section:hover {
            color: white;
            text-decoration: none;
            color: #60dbb9;
        }

    </style>
{% endblock %}

{% block body %}
    {% block navbar %}
    <div class="container-fluid" style="max-width: 70%;">
        <!-- Top nav bar -->
        <nav class="navbar navbar-light" style="margin-top: 10px;">
            <i class="fa fa-shopping-bag"></i>
            <p>Shopping Login</p>
        </nav>
    </div>
    {% endblock %}

    <!-- Form -->
    {% block content %}
    <div class="container-fluid justify-content-center" style="background-color: #42f5c2; width: 100%;">
        <div class="container-fluid" style="max-width: 70%; background-color: #42f5c2;">
            <div class="row justify-content-center">
                <div class="col-6 logo-section-container" style="text-align: center; font-size: 80px; margin-top: 5%; color: white; max-width: 400px;">
                    <a href="{% url 'index' %}" class="logo-section">
                        <i class="fa fa-shopping-bag"></i>
                        <p>Shopping</p>
                    </a>
                </div>
                <div class="col-6" style="min-width: 400px;">
                    <form class="form-group" action="" method="post" style="background-color: white; padding: 20px 20px 20px 20px; margin-top: 15px; border-radius: 7px;">
                        {% csrf_token %}
                        <div class="" style="margin: 40px 20px 2px 2px;">
                            <p>
                                <label for="id_full_name">Username</label>
                                <input autofocus id="id_full_name" type="text" name="username" maxlength="100" required class="form-control">
                            </p>

                            <p>
                                <label for="id_password">Password</label>
                                <input id="id_password" type="password" name="password" maxlength="100" required class="form-control">
                            </p>

                            <a href="#">
                                <p>Forgot password</p>
                            </a>

                            <p style="margin-left: 3px; color: grey">{{ message }}</p>

                        </div>
                        <input id="login-btn" type="submit" class="btn" name="login" value="Log In">
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block bottom_footer %}
        <!-- Bottom footer -->
        <div class="container-fluid" style="max-width: 68%; margin-top: 15px;">
            <div class="row">
                <div class="col-sm">
                    <p style="margin-bottom: 0rem; color: #575757;" class="nav-item nav-link">Shopping Country & Region:</p>
                    <div class="country-icons">
                        <div class="d-flex p-2">
                            <img style="margin-left: 15px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333299-3b1e9e80-dff7-11ea-8de5-2d988eae2df1.jpg" alt="singapore-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333392-f34c4700-dff7-11ea-9aac-0dded940d1af.png" alt="malaysia-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333394-f47d7400-dff7-11ea-8e5d-7dee9ccee504.png" alt="indonesia-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333395-f5aea100-dff7-11ea-8fc5-5e88bf8ff034.png" alt="taiwan-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333396-f6dfce00-dff7-11ea-9957-912621de1477.png" alt="thailand-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333398-f810fb00-dff7-11ea-96a0-e188ffb3578d.png" alt="vietnam-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333399-fa735500-dff7-11ea-92ce-2c7503094272.png" alt="philipphines-icon">
                        </div>
                    </div>
                </div>
                <div class="col-sm">
                    <p style="margin-bottom: 0rem; color: #575757;" class="nav-item nav-link">Payment</p>
                    <div class="">
                        <i class="fa fa-cc-visa" style="margin-left: 15px; font-size: 40px;"></i>
                        <i class="fa fa-cc-mastercard" style="margin-left: 15px; font-size: 40px;"></i>
                        <i class="fa fa-cc-amex" style="margin-left: 15px; font-size: 40px;"></i>
                    </div>
                </div>
                <div class="col-sm">
                    <p style="margin-bottom: 0rem; color: #575757;" class="nav-item nav-link">Follow Us On:</p>
                    <div class="">
                        <a href="#" class="follow-links" style="margin-left: 15px;">
                            <span style="color: #3b5998">
                                <i class="fa fa-facebook-square"></i>
                            </span>
                            <span style="font-size: 13px; color: grey;">Facebook</span>
                        </a>
                    </div>
                    <div class="">
                        <a href="#" class="follow-links" style="margin-left: 15px;">
                            <span style="color: brown;">
                                <i class="fa fa-instagram"></i>
                            </span>
                            <span style="font-size: 13px; color: grey;">Instagram</span>
                        </a>
                    </div>
                    <div class="">
                        <a href="#" class="follow-links" style="margin-left: 15px;">
                            <span style="color: #0072b1">
                                <i class="fa fa-linkedin-square"></i>
                            </span>
                            <span style="font-size: 13px; color: grey;">LinkedIn</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
{% endblock %}

capstone/shopping/templates/shopping/signup.html
{% extends "shopping/layout.html" %}
{% load static %}

{% block title %}
    Shopping | Sign Up
{% endblock %}

{% block script %}
    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

    <script>
        $(function () {
            $('#datetimepicker4').datetimepicker({
                format: 'L'
            });
        });
    </script>

{% endblock %}

{% block style %}
    <style>
        .navbar p {
            font-size: 30px;
        }

        #signup-btn {
            width: 100%;
            margin-top: 20px;
            background-color: #42f5c2;
            color: white;
        }

        #signup-btn:hover {
            background-color: #60dbb9;
        }

        .logo-section {
            color: white;
            text-docoration: none;
        }

        .logo-section-container:hover {
            color: white;
            text-decoration: none;
            color: #60dbb9;
        }

        .logo-section:hover {
            color: white;
            text-decoration: none;
            color: #60dbb9;
        }

    </style>
{% endblock %}

{% block body %}
    {% block navbar %}
    <div class="container-fluid" style="max-width: 70%;">
        <!-- Top nav bar -->
        <nav class="navbar navbar-light" style="margin-top: 10px;">
            <i class="fa fa-shopping-bag"></i>
            <p>Shopping Sign Up</p>
        </nav>
    </div>
    {% endblock %}

    <!-- Form -->
    {% block content %}
        <div class="container-fluid justify-content-center" style="background-color: #42f5c2; width: 100%;">
            <div class="container-fluid" style="max-width: 70%; background-color: #42f5c2;">
                <div class="row justify-content-center">
                    <div class="col-6 logo-section-container" style="text-align: center; font-size: 80px; margin-top: 20%; color: white; max-width: 400px;">
                        <a href="{% url 'index' %}" class="logo-section">
                            <i class="fa fa-shopping-bag"></i>
                            <p>Shopping</p>
                        </a>
                    </div>
                    <div class="col-6" style="min-width: 400px;">
                        <form class="form-group" action="{% url 'signup' %}" method="post" style="background-color: white; padding: 20px 20px 20px 20px; margin-top: 15px; border-radius: 7px;">
                            {% csrf_token %}
                            <div class="" style="margin: 20px 20px 2px 2px;">
                                <p>
                                    <label for="id_username">Username</label>
                                    <input id="id_username" type="text" name="username" maxlength="100" required class="form-control">
                                    <p style="margin-left: 3px; color: grey"><i>{{ message_username }}</i></p>
                                </p>

                                <p>
                                    <label for="id_password">Password</label>
                                    <input id="id_password" type="password" name="password" maxlength="100" required class="form-control">
                                    <p style="margin-left: 3px; color: grey"><i>{{ message_password }}</i></p>
                                </p>

                                <p>
                                    <label for="id_confirmation">Re-Enter Password</label>
                                    <input id="id_confirmation" type="password" name="confirmation" maxlength="100" required class="form-control">
                                </p>

                                <p>
                                    <label for="id_full_name">Full Name</label>
                                    <input id="id_full_name" type="text" name="full_name" maxlength="100" required class="form-control">
                                </p>



                                <p>
                                    <label for="id_gender">Gender</label>
                                    <select id="id_full_name" class="form-control" name="gender">
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                        <option value="Other">Other</option>
                                    </select>
                                </p>

                                <p>
                                    <label for="id_phone_number">Phone Number</label>
                                    <input id="id_phone_number" type="text" name="phone_number" maxlength="100" required class="form-control">
                                </p>

                                <p>
                                    <label for="id_email">Email</label>
                                    <input id="id_email" type="text" name="email" maxlength="100" required class="form-control">
                                </p>

                                <p style="margin-bottom: 2px;">
                                    <label for="id_birthday" class="label">Date of Birth</label>
                                </p>
                            </div>

                            <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
                                <input type="text" name="date_of_birth" class="form-control datetimepicker-input" data-target="#datetimepicker4"/>
                                <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                                    <div class="input-group-text">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                </div>
                            </div>

                            <input id="signup-btn" style="" type="submit" class="btn" name="Sign Up" value="Sign Up">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block bottom_footer %}
        <!-- Bottom footer -->
        <div class="container-fluid " style="max-width: 68%; margin-top: 15px;">
            <div class="row">
                <div class="col-sm">
                    <p style="margin-bottom: 0rem; color: #575757;" class="nav-item nav-link">Shopping Country & Region:</p>
                    <div class="country-icons">
                        <div class="d-flex p-2">
                            <img style="margin-left: 15px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333299-3b1e9e80-dff7-11ea-8de5-2d988eae2df1.jpg" alt="singapore-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333392-f34c4700-dff7-11ea-9aac-0dded940d1af.png" alt="malaysia-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333394-f47d7400-dff7-11ea-8e5d-7dee9ccee504.png" alt="indonesia-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333395-f5aea100-dff7-11ea-8fc5-5e88bf8ff034.png" alt="taiwan-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333396-f6dfce00-dff7-11ea-9957-912621de1477.png" alt="thailand-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333398-f810fb00-dff7-11ea-96a0-e188ffb3578d.png" alt="vietnam-icon">
                            <img style="margin-left: 5px; height: 30px; width: 30px; border-radius: 15px;" src="https://user-images.githubusercontent.com/59989652/90333399-fa735500-dff7-11ea-92ce-2c7503094272.png" alt="philipphines-icon">
                        </div>
                    </div>
                </div>
                <div class="col-sm">
                    <p style="margin-bottom: 0rem; color: #575757;" class="nav-item nav-link">Payment</p>
                    <div class="">
                        <i class="fa fa-cc-visa" style="margin-left: 15px; font-size: 40px;"></i>
                        <i class="fa fa-cc-mastercard" style="margin-left: 15px; font-size: 40px;"></i>
                        <i class="fa fa-cc-amex" style="margin-left: 15px; font-size: 40px;"></i>
                    </div>
                </div>
                <div class="col-sm">
                    <p style="margin-bottom: 0rem; color: #575757;" class="nav-item nav-link">Follow Us On:</p>
                    <div class="">
                        <a href="#" class="follow-links" style="margin-left: 15px;">
                            <span style="color: #3b5998">
                                <i class="fa fa-facebook-square"></i>
                            </span>
                            <span style="font-size: 13px; color: grey;">Facebook</span>
                        </a>
                    </div>
                    <div class="">
                        <a href="#" class="follow-links" style="margin-left: 15px;">
                            <span style="color: brown;">
                                <i class="fa fa-instagram"></i>
                            </span>
                            <span style="font-size: 13px; color: grey;">Instagram</span>
                        </a>
                    </div>
                    <div class="">
                        <a href="#" class="follow-links" style="margin-left: 15px;">
                            <span style="color: #0072b1">
                                <i class="fa fa-linkedin-square"></i>
                            </span>
                            <span style="font-size: 13px; color: grey;">LinkedIn</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
{% endblock %}